version: '3'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=password
      - DB_NAME=bookings
    volumes:
      - ./booking_api:/app

  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: bookings
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
